/**
 * SalesTim API
 * The Microsoft Teams Governance API 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@salestim.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SalesTimApi);
  }
}(this, function(expect, SalesTimApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SalesTimApi.StoreCategoryLabel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StoreCategoryLabel', function() {
    it('should create an instance of StoreCategoryLabel', function() {
      // uncomment below and update the code to test StoreCategoryLabel
      //var instane = new SalesTimApi.StoreCategoryLabel();
      //expect(instance).to.be.a(SalesTimApi.StoreCategoryLabel);
    });

    it('should have the property enUs (base name: "en-us")', function() {
      // uncomment below and update the code to test the property enUs
      //var instane = new SalesTimApi.StoreCategoryLabel();
      //expect(instance).to.be();
    });

    it('should have the property frFr (base name: "fr-fr")', function() {
      // uncomment below and update the code to test the property frFr
      //var instane = new SalesTimApi.StoreCategoryLabel();
      //expect(instance).to.be();
    });

  });

}));
