title: SalesTim API SDK
description: This repository contains the SalesTim API SDK for various programming languages and platforms.
theme: jekyll-theme-minimal
logo: https://store.salestim.com/color.png
show_downloads: false