/**
 * SalesTim API
 * The Microsoft Teams Governance API 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@salestim.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PluginTemplateConfiguration model module.
 * @module model/PluginTemplateConfiguration
 * @version 1.0.0
 */
class PluginTemplateConfiguration {
    /**
     * Constructs a new <code>PluginTemplateConfiguration</code>.
     * Main template properties
     * @alias module:model/PluginTemplateConfiguration
     */
    constructor() { 
        
        PluginTemplateConfiguration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PluginTemplateConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PluginTemplateConfiguration} obj Optional instance to populate.
     * @return {module:model/PluginTemplateConfiguration} The populated <code>PluginTemplateConfiguration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PluginTemplateConfiguration();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('createdBy')) {
                obj['createdBy'] = ApiClient.convertToType(data['createdBy'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('secret')) {
                obj['secret'] = ApiClient.convertToType(data['secret'], 'String');
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * The plugin name
 * @member {String} name
 */
PluginTemplateConfiguration.prototype['name'] = undefined;

/**
 * The plugin description
 * @member {String} description
 */
PluginTemplateConfiguration.prototype['description'] = undefined;

/**
 * The ID (Fron Azure AD) of the user that created the plugin
 * @member {String} createdBy
 */
PluginTemplateConfiguration.prototype['createdBy'] = undefined;

/**
 * The date of creation of the plugin
 * @member {Date} createdAt
 */
PluginTemplateConfiguration.prototype['createdAt'] = undefined;

/**
 * The plugin ID, auto-generated at creation
 * @member {String} id
 */
PluginTemplateConfiguration.prototype['id'] = undefined;

/**
 * The plugin secret, auto-generated at creation. It may also be regenerated later. Be careful, this property is only available at creation or after an explicit regeneration. 
 * @member {String} secret
 */
PluginTemplateConfiguration.prototype['secret'] = undefined;

/**
 * The plugin status, enabled or disabled
 * @member {Boolean} enabled
 * @default true
 */
PluginTemplateConfiguration.prototype['enabled'] = true;






export default PluginTemplateConfiguration;

