/**
 * SalesTim API
 * The Microsoft Teams Governance API 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@salestim.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PluginTemplateConfiguration from './PluginTemplateConfiguration';

/**
 * The Plugin model module.
 * @module model/Plugin
 * @version 1.0.0
 */
class Plugin {
    /**
     * Constructs a new <code>Plugin</code>.
     * A platform plugin (aka \&quot;Virtual Apps\&quot;)
     * @alias module:model/Plugin
     */
    constructor() { 
        
        Plugin.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Plugin</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Plugin} obj Optional instance to populate.
     * @return {module:model/Plugin} The populated <code>Plugin</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Plugin();

            if (data.hasOwnProperty('templateConfiguration')) {
                obj['templateConfiguration'] = PluginTemplateConfiguration.constructFromObject(data['templateConfiguration']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/PluginTemplateConfiguration} templateConfiguration
 */
Plugin.prototype['templateConfiguration'] = undefined;






export default Plugin;

