/**
 * SalesTim API
 * The Microsoft Teams Governance API 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@salestim.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProvisioningRequestOnBehalfOfRequester from './ProvisioningRequestOnBehalfOfRequester';
import ProvisioningRequestRequestedMembers from './ProvisioningRequestRequestedMembers';

/**
 * The ProvisioningRequest model module.
 * @module model/ProvisioningRequest
 * @version 1.0.0
 */
class ProvisioningRequest {
    /**
     * Constructs a new <code>ProvisioningRequest</code>.
     * A request to provision a team based on a template from your corporate catalog
     * @alias module:model/ProvisioningRequest
     * @param templateId {String} The template ID
     * @param requestedTeamName {String} Requested team name
     */
    constructor(templateId, requestedTeamName) { 
        
        ProvisioningRequest.initialize(this, templateId, requestedTeamName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, templateId, requestedTeamName) { 
        obj['templateId'] = templateId;
        obj['requestedTeamName'] = requestedTeamName;
    }

    /**
     * Constructs a <code>ProvisioningRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProvisioningRequest} obj Optional instance to populate.
     * @return {module:model/ProvisioningRequest} The populated <code>ProvisioningRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProvisioningRequest();

            if (data.hasOwnProperty('templateId')) {
                obj['templateId'] = ApiClient.convertToType(data['templateId'], 'String');
            }
            if (data.hasOwnProperty('requestedTeamName')) {
                obj['requestedTeamName'] = ApiClient.convertToType(data['requestedTeamName'], 'String');
            }
            if (data.hasOwnProperty('requestedTeamDescription')) {
                obj['requestedTeamDescription'] = ApiClient.convertToType(data['requestedTeamDescription'], 'String');
            }
            if (data.hasOwnProperty('requestedTeamWelcomeMessage')) {
                obj['requestedTeamWelcomeMessage'] = ApiClient.convertToType(data['requestedTeamWelcomeMessage'], 'String');
            }
            if (data.hasOwnProperty('requestedMembers')) {
                obj['requestedMembers'] = ApiClient.convertToType(data['requestedMembers'], [ProvisioningRequestRequestedMembers]);
            }
            if (data.hasOwnProperty('requestedOwners')) {
                obj['requestedOwners'] = ApiClient.convertToType(data['requestedOwners'], [ProvisioningRequestRequestedMembers]);
            }
            if (data.hasOwnProperty('onBehalfOfRequester')) {
                obj['onBehalfOfRequester'] = ProvisioningRequestOnBehalfOfRequester.constructFromObject(data['onBehalfOfRequester']);
            }
        }
        return obj;
    }


}

/**
 * The template ID
 * @member {String} templateId
 */
ProvisioningRequest.prototype['templateId'] = undefined;

/**
 * Requested team name
 * @member {String} requestedTeamName
 */
ProvisioningRequest.prototype['requestedTeamName'] = undefined;

/**
 * Requested team description
 * @member {String} requestedTeamDescription
 */
ProvisioningRequest.prototype['requestedTeamDescription'] = undefined;

/**
 * Requested team welcome message
 * @member {String} requestedTeamWelcomeMessage
 */
ProvisioningRequest.prototype['requestedTeamWelcomeMessage'] = undefined;

/**
 * Requested members as an array of objects
 * @member {Array.<module:model/ProvisioningRequestRequestedMembers>} requestedMembers
 */
ProvisioningRequest.prototype['requestedMembers'] = undefined;

/**
 * Requested owners as an array of users. User identifier could be its ID, UPN or email.
 * @member {Array.<module:model/ProvisioningRequestRequestedMembers>} requestedOwners
 */
ProvisioningRequest.prototype['requestedOwners'] = undefined;

/**
 * @member {module:model/ProvisioningRequestOnBehalfOfRequester} onBehalfOfRequester
 */
ProvisioningRequest.prototype['onBehalfOfRequester'] = undefined;






export default ProvisioningRequest;

