/**
 * SalesTim API
 * The Microsoft Teams Governance API 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@salestim.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProvisioningRequestRequestedMembers model module.
 * @module model/ProvisioningRequestRequestedMembers
 * @version 1.0.0
 */
class ProvisioningRequestRequestedMembers {
    /**
     * Constructs a new <code>ProvisioningRequestRequestedMembers</code>.
     * @alias module:model/ProvisioningRequestRequestedMembers
     */
    constructor() { 
        
        ProvisioningRequestRequestedMembers.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProvisioningRequestRequestedMembers</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProvisioningRequestRequestedMembers} obj Optional instance to populate.
     * @return {module:model/ProvisioningRequestRequestedMembers} The populated <code>ProvisioningRequestRequestedMembers</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProvisioningRequestRequestedMembers();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('upn')) {
                obj['upn'] = ApiClient.convertToType(data['upn'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
        }
        return obj;
    }


}

/**
 * User ID
 * @member {String} id
 */
ProvisioningRequestRequestedMembers.prototype['id'] = undefined;

/**
 * User UPN
 * @member {String} upn
 */
ProvisioningRequestRequestedMembers.prototype['upn'] = undefined;

/**
 * User email
 * @member {String} email
 */
ProvisioningRequestRequestedMembers.prototype['email'] = undefined;






export default ProvisioningRequestRequestedMembers;

