/**
 * SalesTim API
 * The Microsoft Teams Governance API 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@salestim.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StoreCategoryLabel from './StoreCategoryLabel';

/**
 * The StoreCategory model module.
 * @module model/StoreCategory
 * @version 1.0.0
 */
class StoreCategory {
    /**
     * Constructs a new <code>StoreCategory</code>.
     * A category of templates from the public template store
     * @alias module:model/StoreCategory
     */
    constructor() { 
        
        StoreCategory.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StoreCategory</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StoreCategory} obj Optional instance to populate.
     * @return {module:model/StoreCategory} The populated <code>StoreCategory</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StoreCategory();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = StoreCategoryLabel.constructFromObject(data['label']);
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Category ID
 * @member {String} id
 */
StoreCategory.prototype['id'] = undefined;

/**
 * @member {module:model/StoreCategoryLabel} label
 */
StoreCategory.prototype['label'] = undefined;

/**
 * Category slug used for clean and seo-friendly urls
 * @member {String} slug
 */
StoreCategory.prototype['slug'] = undefined;






export default StoreCategory;

