/**
 * SalesTim API
 * The Microsoft Teams Governance API 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@salestim.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StoreTemplateTemplateConfiguration model module.
 * @module model/StoreTemplateTemplateConfiguration
 * @version 1.0.0
 */
class StoreTemplateTemplateConfiguration {
    /**
     * Constructs a new <code>StoreTemplateTemplateConfiguration</code>.
     * Main template properties
     * @alias module:model/StoreTemplateTemplateConfiguration
     */
    constructor() { 
        
        StoreTemplateTemplateConfiguration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StoreTemplateTemplateConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StoreTemplateTemplateConfiguration} obj Optional instance to populate.
     * @return {module:model/StoreTemplateTemplateConfiguration} The populated <code>StoreTemplateTemplateConfiguration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StoreTemplateTemplateConfiguration();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Template ID
 * @member {String} id
 */
StoreTemplateTemplateConfiguration.prototype['id'] = undefined;






export default StoreTemplateTemplateConfiguration;

