/**
 * SalesTim API
 * The Microsoft Teams Governance API 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@salestim.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StoreCategoryLabel model module.
 * @module model/StoreCategoryLabel
 * @version 1.0.0
 */
class StoreCategoryLabel {
    /**
     * Constructs a new <code>StoreCategoryLabel</code>.
     * Collection of localized category labels
     * @alias module:model/StoreCategoryLabel
     */
    constructor() { 
        
        StoreCategoryLabel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StoreCategoryLabel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StoreCategoryLabel} obj Optional instance to populate.
     * @return {module:model/StoreCategoryLabel} The populated <code>StoreCategoryLabel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StoreCategoryLabel();

            if (data.hasOwnProperty('en-us')) {
                obj['en-us'] = ApiClient.convertToType(data['en-us'], 'String');
            }
            if (data.hasOwnProperty('fr-fr')) {
                obj['fr-fr'] = ApiClient.convertToType(data['fr-fr'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Category label localized for en-us.
 * @member {String} en-us
 */
StoreCategoryLabel.prototype['en-us'] = undefined;

/**
 * Category label localized for fr-fr.
 * @member {String} fr-fr
 */
StoreCategoryLabel.prototype['fr-fr'] = undefined;






export default StoreCategoryLabel;

