/**
 * SalesTim API
 * The Microsoft Teams Governance API 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@salestim.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TemplateIdentifier model module.
 * @module model/TemplateIdentifier
 * @version 1.0.0
 */
class TemplateIdentifier {
    /**
     * Constructs a new <code>TemplateIdentifier</code>.
     * Object defining the ID of a template
     * @alias module:model/TemplateIdentifier
     */
    constructor() { 
        
        TemplateIdentifier.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TemplateIdentifier</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TemplateIdentifier} obj Optional instance to populate.
     * @return {module:model/TemplateIdentifier} The populated <code>TemplateIdentifier</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TemplateIdentifier();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * A template ID
 * @member {String} id
 */
TemplateIdentifier.prototype['id'] = undefined;






export default TemplateIdentifier;

