/* 
 * SalesTim API
 *
 * The Microsoft Teams Governance API 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@salestim.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing CatalogTemplate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CatalogTemplateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CatalogTemplate
        //private CatalogTemplate instance;

        public CatalogTemplateTests()
        {
            // TODO uncomment below to create an instance of CatalogTemplate
            //instance = new CatalogTemplate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CatalogTemplate
        /// </summary>
        [Fact]
        public void CatalogTemplateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CatalogTemplate
            //Assert.IsInstanceOfType<CatalogTemplate> (instance, "variable 'instance' is a CatalogTemplate");
        }


        /// <summary>
        /// Test the property 'TemplateConfiguration'
        /// </summary>
        [Fact]
        public void TemplateConfigurationTest()
        {
            // TODO unit test for the property 'TemplateConfiguration'
        }

    }

}
