/* 
 * SalesTim API
 *
 * The Microsoft Teams Governance API 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@salestim.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ProvisioningRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProvisioningRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProvisioningRequest
        //private ProvisioningRequest instance;

        public ProvisioningRequestTests()
        {
            // TODO uncomment below to create an instance of ProvisioningRequest
            //instance = new ProvisioningRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProvisioningRequest
        /// </summary>
        [Fact]
        public void ProvisioningRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProvisioningRequest
            //Assert.IsInstanceOfType<ProvisioningRequest> (instance, "variable 'instance' is a ProvisioningRequest");
        }


        /// <summary>
        /// Test the property 'TemplateId'
        /// </summary>
        [Fact]
        public void TemplateIdTest()
        {
            // TODO unit test for the property 'TemplateId'
        }
        /// <summary>
        /// Test the property 'RequestedTeamName'
        /// </summary>
        [Fact]
        public void RequestedTeamNameTest()
        {
            // TODO unit test for the property 'RequestedTeamName'
        }
        /// <summary>
        /// Test the property 'RequestedTeamDescription'
        /// </summary>
        [Fact]
        public void RequestedTeamDescriptionTest()
        {
            // TODO unit test for the property 'RequestedTeamDescription'
        }
        /// <summary>
        /// Test the property 'RequestedTeamWelcomeMessage'
        /// </summary>
        [Fact]
        public void RequestedTeamWelcomeMessageTest()
        {
            // TODO unit test for the property 'RequestedTeamWelcomeMessage'
        }
        /// <summary>
        /// Test the property 'RequestedMembers'
        /// </summary>
        [Fact]
        public void RequestedMembersTest()
        {
            // TODO unit test for the property 'RequestedMembers'
        }
        /// <summary>
        /// Test the property 'RequestedOwners'
        /// </summary>
        [Fact]
        public void RequestedOwnersTest()
        {
            // TODO unit test for the property 'RequestedOwners'
        }
        /// <summary>
        /// Test the property 'OnBehalfOfRequester'
        /// </summary>
        [Fact]
        public void OnBehalfOfRequesterTest()
        {
            // TODO unit test for the property 'OnBehalfOfRequester'
        }

    }

}
