/* 
 * SalesTim API
 *
 * The Microsoft Teams Governance API 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@salestim.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing StoreCategoryLabel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StoreCategoryLabelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StoreCategoryLabel
        //private StoreCategoryLabel instance;

        public StoreCategoryLabelTests()
        {
            // TODO uncomment below to create an instance of StoreCategoryLabel
            //instance = new StoreCategoryLabel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StoreCategoryLabel
        /// </summary>
        [Fact]
        public void StoreCategoryLabelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StoreCategoryLabel
            //Assert.IsInstanceOfType<StoreCategoryLabel> (instance, "variable 'instance' is a StoreCategoryLabel");
        }


        /// <summary>
        /// Test the property 'EnUs'
        /// </summary>
        [Fact]
        public void EnUsTest()
        {
            // TODO unit test for the property 'EnUs'
        }
        /// <summary>
        /// Test the property 'FrFr'
        /// </summary>
        [Fact]
        public void FrFrTest()
        {
            // TODO unit test for the property 'FrFr'
        }

    }

}
