/* 
 * SalesTim API
 *
 * The Microsoft Teams Governance API 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@salestim.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing TemplateIdentifier
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplateIdentifierTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemplateIdentifier
        //private TemplateIdentifier instance;

        public TemplateIdentifierTests()
        {
            // TODO uncomment below to create an instance of TemplateIdentifier
            //instance = new TemplateIdentifier();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplateIdentifier
        /// </summary>
        [Fact]
        public void TemplateIdentifierInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TemplateIdentifier
            //Assert.IsInstanceOfType<TemplateIdentifier> (instance, "variable 'instance' is a TemplateIdentifier");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
