/* 
 * SalesTim API
 *
 * The Microsoft Teams Governance API 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@salestim.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing JobsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class JobsApiTests : IDisposable
    {
        private JobsApi instance;

        public JobsApiTests()
        {
            instance = new JobsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' JobsApi
            //Assert.IsType(typeof(JobsApi), instance, "instance is a JobsApi");
        }

        
        /// <summary>
        /// Test CreateProvisioningJob
        /// </summary>
        [Fact]
        public void CreateProvisioningJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProvisioningRequest provisioningRequest = null;
            //var response = instance.CreateProvisioningJob(provisioningRequest);
            //Assert.IsType<Job> (response, "response is Job");
        }
        
        /// <summary>
        /// Test GetJob
        /// </summary>
        [Fact]
        public void GetJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetJob(id);
            //Assert.IsType<Job> (response, "response is Job");
        }
        
    }

}
